DP-1528 warn on duplicateRemovalOrderColumn not present in the schema
celonis/kafka-ems-connector pull request #46
Opened 2023-08-08 15:10 UTC by piatekm

### Description

Log a warning when uploading a file which schema does not contain a field configured as duplicateRemovalOrderColumn.

### Testing
- [x] existing unit tests updated
- [x] manual test with running connector and wrongly configured ordering field

2023-08-08 15:11 UTC, piatekm commented on connector/src/main/scala/com/celonis/kafka/connect/ems/storage/Uploader.scala
> +  def getOrderFieldName: Option[String]
It's not too nice to add this to the `Uploader'`s contract, on the other hand I wanted to avoid doing that on record's level (because it would cause a mess in the logs) and that was the easiest way to do it that I found.

2023-08-23 09:04 UTC, afiore approved these changes
Looks good!

2023-08-23 09:19 UTC, afiore requested changes

2023-08-23 09:19 UTC, afiore commented on connector/src/main/scala/com/celonis/kafka/connect/ems/storage/WriterManager.scala
> +          A.delay(logger.warn(
Actually, how come this method returns `Unit` and not `IO[Unit]`?  isn't it the case that the call to `A.delay(...)` will be discarded, and no log will be printed?

2023-08-23 10:28 UTC, piatekm commented on connector/src/main/scala/com/celonis/kafka/connect/ems/storage/WriterManager.scala
> +          A.delay(logger.warn(
You're right, I added a fix so that this function returns a `F[Unit]` now. 

On the other hand, as already discussed on Slack - it's strange that the compiler allowed a non-unit value to be discarded, as we have proper flags defined (both for [scala212](https://github.com/celonis/kafka-ems-connector/blob/main/project/Settings.scala#L96) and [scala213](https://github.com/celonis/kafka-ems-connector/blob/main/project/Settings.scala#L131).
It's something to be investigated, but it's not a blocker for the current PR.

2023-08-23 10:33 UTC, piatekm commented
I performed manual tests and the warning is produced properly :heavy_check_mark:

2023-08-23 10:54 UTC, afiore approved these changes

2023-08-23 10:54 UTC, merged